<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="ISCHLAPHP21792" failures="2" tests="8" name="Personal Loan" time="0.136" errors="0" timestamp="2024-04-23T14:39:46 IST">
  <testcase classname="TestNG.Day1" name="Demo" time="0.011"/>
  <testcase classname="TestNG.Day2" name="thirdTest" time="0.002"/>
  <testcase classname="TestNG.Day4" name="APILoginHomeLoan" time="0.003"/>
  <testcase classname="TestNG.Day4" name="MoblieLoanDepartment" time="0.013">
    <skipped/>
  </testcase> <!-- MoblieLoanDepartment -->
  <testcase classname="TestNG.Day4" name="MoblieLoanDepartment" time="0.002">
    <skipped/>
  </testcase> <!-- MoblieLoanDepartment -->
  <testcase classname="TestNG.Day4" name="MoblieLoanDepartment" time="0.002">
    <skipped/>
  </testcase> <!-- MoblieLoanDepartment -->
  <testcase classname="TestNG.Day4" name="MoblieLoanDepartment" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Day4.MoblieLoanDepartment(Day4.java:28)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MoblieLoanDepartment -->
  <testcase classname="TestNG.Day4" name="MoblieLoginHomeLoan" time="0.002">
    <failure type="java.lang.AssertionError" message="expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at TestNG.Day4.MoblieLoginHomeLoan(Day4.java:14)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- MoblieLoginHomeLoan -->
  <testcase classname="TestNG.Day1" name="secondTest" time="0.0">
    <ignored/>
  </testcase> <!-- secondTest -->
</testsuite> <!-- Personal Loan -->
